# Site settings
title: "I'm Long"
description: "Tôi viết về những lĩnh vực tôi thích và muốn tìm hiểu thêm về nó."
baseurl: "" 
url: ""
author: "Long Vox"
intro: "<b><b>I'm Long</b></b> nơi ghi chép lại những câu chuyện về những ngày rãnh rỗi của tôi."

# Build settings
kramdown:
  input: GFM
permalink: /:title/

# Third-party services
# just leave empty to disable it
google_analytics: UA-80507572-2
disqus: true
disqus_shortname: longvox

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
